# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'memuDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
pod 'Alamofire'
pod 'SwiftyJSON'
  # Pods for memuDemo

  target 'memuDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'memuDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
